### ISSUE TITLE
Issues with InfiniteWP

### ISSUE THREAD

**Issue by galbaras** [angelleye/angelleye-updater#28]
I use InfiniteWP to update my sites, and get delayed listing of outstanding updates (of the PayPal for WooCommerce plugin), and incorrect plugin data retrieval.

I suspect this is due to the use of the updater plugin, and specifically, to its use of caching.

Is there some way to disable caching, even for testing purposes, and/or troubleshoot this some other way?

**Comment by devchristina2** [comment]
Hi @galbaras,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support through GitHub and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
