### ISSUE TITLE
infinite plugin update loop: v2.0.19 is actually v2.0.18

### ISSUE THREAD

**Issue by R-Adrian** [angelleye/angelleye-updater#30]
```
https://updates.angelleye.com/ae-updater/angelleye-updater/angelleye-updater-v2.0.19.zip
https://updates.angelleye.com/ae-updater/angelleye-updater/angelleye-updater.zip
```
SHA256 sum for both files= 65ba758c3e9e45e5d5bfe856fe1c759eb0153bd792aba5bdcf370a09dfa7afe9

the plugin version number inside the archives is actually 2.0.18 and this causes WordPress to go in an infinite loop - it auto-updates the plugin every time it runs the automatic updater schedule and also prompts for update every time i manually check the plugins.

```
https://github.com/angelleye/angelleye-updater/blob/master/angelleye-updater.php
( line 22 )
define('AU_PLUGIN_VERSION', '2.0.18');`

https://github.com/angelleye/angelleye-updater/blob/master/includes/class-angelleye-updater.php
( line 70 )
   $this->version = '2.0.18';
```
I had to change these manually on my system to 2.0.19 and it finally stopped the looping update notification.

![image](https://github.com/angelleye/angelleye-updater/assets/16319504/dd9d9dc0-8914-4386-b479-bf7b05cfab93)

**Comment by galbaras** [comment]
+1. This isn't an issue with InfiniteWP at all. WordPress keeps suggesting to update after successfully updating the plugin.

**Comment by R-Adrian** [comment]
side note / comment:
> This isn't an issue with InfiniteWP at all.

i had to look up what InfiniteWP is ... and no, my use of the word "infinite" in the topic name there is not related to that, i simply used it to describe the infinite loop that WP is doing with version 2.0.19 ... a veeeeeryyy slooow loop (automatic update happens only every few hours) but still technically a loop.

**Comment by galbaras** [comment]
Oh, sorry. I use InfiniteWP and came here looking for this issue after it seemed to fail to update the plugin 😄 

I've followed your breadcrumb trail and hacked the respective files, so my sites are OK now. Thank you for the pointers.

Did you say automatic updates?! Brrr...

**Comment by kcppdevelopers** [comment]
I've addressed this problem and rolled out a new version.
